name: Kernel Build

on:
  workflow_dispatch:
    inputs:
      variant:
        description: "Build Variant"
        required: true
        default: "perf"
        type: choice
        options:
          - "perf"
          - "batt"
      ksu:
        description: "KernelSU Variant"
        required: true
        default: "ksu"
        type: choice
        options:
          - "ksu"
          - "ksu-next"
          - "non-ksu"

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Free up workflow space
      run: |
        curl -L -o util_free_space.sh https://raw.githubusercontent.com/apache/arrow/main/ci/scripts/util_free_space.sh
        chmod +x util_free_space.sh
        ./util_free_space.sh

    - name: Import Kernel Source
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install Required Packages
      run: .github/scripts/ci.sh prepare_env

    - name: Setup ccache
      uses: actions/cache@v4
      with:
        path: .ccache
        key: ${{ runner.os }}-ccache-${{ inputs.ksu }}-${{ inputs.variant }}-${{ hashFiles('**/Makefile') }}-${{ github.run_id }}
        restore-keys: |
          ${{ runner.os }}-ccache-${{ inputs.ksu }}-${{ inputs.variant }}-${{ hashFiles('**/Makefile') }}-
          ${{ runner.os }}-ccache-${{ inputs.ksu }}-${{ inputs.variant }}-

    - name: Get Build Info
      id: info
      run: |
        echo "today=$(date +'%y%m%d')" >> $GITHUB_OUTPUT
        echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
        VERSION=$(grep "^VERSION =" kernel_platform/common/Makefile | awk '{print $3}')
        PATCHLEVEL=$(grep "^PATCHLEVEL =" kernel_platform/common/Makefile | awk '{print $3}')
        SUBLEVEL=$(grep "^SUBLEVEL =" kernel_platform/common/Makefile | awk '{print $3}')
        echo "kernel_ver=$VERSION.$PATCHLEVEL.$SUBLEVEL" >> $GITHUB_OUTPUT

    - name: Kernel Build
      run: |
        export KSU_VARIANT=${{ inputs.ksu }}
        export DEFCONFIG_VARIANT=${{ inputs.variant }}
        export VERSION_SUFFIX="-ZeroX-${{ inputs.variant }}/ci-${{ steps.info.outputs.sha }}"
        
        chmod +x build.sh
        ./build.sh ak3 2>&1 | tee build.log

    - name: Prepare Files
      if: success()
      run: .github/scripts/ci.sh prepare_artifact
      env:
        KSU_VARIANT: ${{ inputs.ksu }}
        DEFCONFIG_VARIANT: ${{ inputs.variant }}
        DATE: ${{ steps.info.outputs.today }}
        SHA: ${{ steps.info.outputs.sha }}
        VERSION: ${{ inputs.version }}

    - name: Upload Artifacts
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.artifact_name }}
        path: ${{ env.final_name }}

    - name: Notify Build Failure
      if: failure()
      run: .github/scripts/ci.sh notify_failure build
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        KSU_VARIANT: ${{ inputs.ksu }}
        DEFCONFIG_VARIANT: ${{ inputs.variant }}
        SHA: ${{ steps.info.outputs.sha }}
        VERSION: ${{ inputs.version }}

    - name: Notify Build Success
      if: success()
      run: .github/scripts/ci.sh notify_success build "${{ steps.info.outputs.kernel_ver }}" "${{ steps.info.outputs.today }}" "${{ steps.info.outputs.sha }}" "" "."
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
